import Head from "next/head";
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillFilePdf,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import Typewriter from 'typewriter-effect';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Manny's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <div className="navbar">
              <li className="hov">Hover Me!
                <ul className="main">
                  <li>manico_y@etna-alternance.net</li>
                  <li>06 51 92 38 52</li>
                </ul>
              </li>
            </div>
            <h1 className="dvp">
            <Typewriter
                options={{
                strings: ['DEVELOPED BY MANNY'],
                autoStart: true,
                loop: true,
              }}
            />
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="name">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Manicord Yannis
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              ETNA Student <br></br>
              Searching for an apprenticeship
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi! I am passionate about computer science and wish to work as an engineer in the field of computer security.I love creating games but also websites.I am also a great sportsman, my favorite fields are MMA, Basketball and US Football
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.instagram.com/mvnnygram__/?next=%2F"
              className="insta">
                <AiFillInstagram />
            </a>
            <a href="https://www.linkedin.com/in/yannis-manicord-601057253/"
              className="linkedin">
                <AiFillLinkedin />
            </a>
            <a href="/cv.pdf"
              className="pdf">
                <AiFillFilePdf />
            </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div className="about">
            <h3 className="text-3xl py-1 dark:text-white ">About Me and What can i do ?</h3>
            <div className="carreer">
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since the beginning of my computer career, I have encountered many difficulties but I have also learned a lot and I am still learning. I am interested in everything that is related to computer science. Here is a small summary of my 
              <span className="text-teal-500"></span>
              <span className="text-teal-500"> skills</span>
            </p>
            </div>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            
              <Image src={design} width={100} height={100} />
              <h3 className="full">
                Fullstack developer
              </h3>
              <p className="py-2">
                I've already created an e-commerce site
              </p>
              <h4 className="py-4 text-teal-600">Language Tools I Use</h4>
              <p className="text-gray-800 py-1">REACT</p>
              <p className="text-gray-800 py-1">CSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="full">
                Hacking
              </h3>
              <p className="py-2">
                Learning about the cybersecurity
              </p>
              <h4 className="py-4 text-teal-600">to learn more about hacking i use ROOT.ME</h4>
              <p className="text-gray-800 py-1">Web client</p>
              <p className="text-gray-800 py-1">Programming</p>
              <p className="text-gray-800 py-1">Web serveur</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="full">language skills</h3>
              <p className="py-2">
                 I have an intermediate level in the following languages 
              </p>
              <h4 className="py-4 text-teal-600">Languages</h4>
              <p className="text-gray-800 py-1">REACT</p>
              <p className="text-gray-800 py-1">JAVASCRIPT</p>
              <p className="text-gray-800 py-1">TYPESCRIPT</p>
              <p className="text-gray-800 py-1">PYTHON</p>
              <p className="text-gray-800 py-1">HTML/CSS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <div className="portofolio">
            <h3 className="text-3xl py-1 dark:text-white ">MY PROJECTS</h3>
            </div>
            <div className="text">
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here's a little view of all 
              <span className="text-teal-500"> work </span>
               I've done for the moment 
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              For sure I would like to have more experience and a lot of <span className="text-teal-500"> big projects </span> to learn more and i will never refuse to learn.
            </p>
            </div>
          </div>
          <div className="container">
        <div className="box">
          <div className="imgBx1">
            <img src="https://pro.root-me.org/squelettes/images/RMP_logo_blanc.png" />
          </div>
          <div className="content">
            <div>
              <h2>ROOT.ME</h2>
              <p>I'm trainig in Web and Programming for the moment</p>
            </div>
          </div>
        </div>
        <div className="box">
          <div className="imgBx2">
            <img src="/zelda.png" />
          </div>
          <div className="content">
            <div>
              <h2>ZELDA GAME</h2>
              <p>I "recreated" the hyrules castle and zelda has to fight multiples Bobokilins before the Boss. I've code it in Typescript only.
              </p>
            </div>
          </div>
        </div>
        <div className="box">
          <div className="imgBx">
            <img src="/nbv-2.png" />
          </div>
          <div className="content">
            <div>
              <h2>E-COMMERCE WEBSITES</h2>
              <p>I've coded a Fullstack website that sell phones accesories.
              </p>
            </div>
          </div>
        </div>
        <div className="box">
          <div className="imgBx">
            <img src="https://icones.pro/wp-content/uploads/2022/07/icone-jeux-et-jeux-video-rouge.png" />
          </div>
          <div className="content">
            <div>
              <h2>MINI GAMES</h2>
              <p>I do mini games in multiples languages.
              </p>
            </div>
          </div>
        </div>
      </div>
        </section>
      </main>
    </div>
  );
}
